"""Added is_suggested to CategoryModel

Revision ID: 13799f874741
Revises: 53830c830b8b
Create Date: 2024-10-02 23:20:53.735905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13799f874741'
down_revision = '53830c830b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_suggested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_suggested')
    # ### end Alembic commands ###
