"""Add CategoryTagModel for category tags

Revision ID: 3fed78a29305
Revises: 555017b5d678
Create Date: 2024-08-16 09:44:16.944854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fed78a29305'
down_revision = '555017b5d678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_tags_id'), 'category_tags', ['id'], unique=False)
    op.create_index(op.f('ix_category_tags_tag'), 'category_tags', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_tags_tag'), table_name='category_tags')
    op.drop_index(op.f('ix_category_tags_id'), table_name='category_tags')
    op.drop_table('category_tags')
    # ### end Alembic commands ###
