"""Added brand_id

Revision ID: 53830c830b8b
Revises: a7615ce4988a
Create Date: 2024-10-02 19:07:34.395420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53830c830b8b'
down_revision = 'a7615ce4988a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('brand_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'brand_id')
    # ### end Alembic commands ###
