"""Added trending score, popularity_index, User_interest_score

Revision ID: 555017b5d678
Revises: 09f498d8d464
Create Date: 2024-08-16 08:53:18.179025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555017b5d678'
down_revision = '09f498d8d464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('trending_score', sa.Float(), nullable=True))
    op.add_column('categories', sa.Column('popularity_index', sa.Float(), nullable=True))
    op.add_column('categories', sa.Column('user_interest_score', sa.Float(), nullable=True))
    op.drop_index('ix_categories_slug', table_name='categories')
    op.create_unique_constraint(None, 'categories', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index('ix_categories_slug', 'categories', ['slug'], unique=True)
    op.drop_column('categories', 'user_interest_score')
    op.drop_column('categories', 'popularity_index')
    op.drop_column('categories', 'trending_score')
    # ### end Alembic commands ###
