"""Added CategoryAnalyicsModel, CategoryFeatureModel and ProdutModel

Revision ID: a7615ce4988a
Revises: f5a851c442f7
Create Date: 2024-10-02 14:02:06.750704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7615ce4988a'
down_revision = 'f5a851c442f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_analytics_id'), 'category_analytics', ['id'], unique=False)
    op.create_table('category_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('feature_start_date', sa.DateTime(), nullable=False),
    sa.Column('feature_end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_features_id'), 'category_features', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.add_column('categories', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('meta_description', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('meta_keywords', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('featured_rank', sa.Integer(), nullable=True))
    op.alter_column('categories', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('category_tags', sa.Column('tag_weight', sa.Float(), nullable=True))
    op.add_column('category_tags', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('category_tags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user_data', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_data', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user_data', sa.Column('purchase_history', sa.String(), nullable=True))
    op.add_column('user_data', sa.Column('wishlist', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'wishlist')
    op.drop_column('user_data', 'purchase_history')
    op.drop_column('user_data', 'updated_at')
    op.drop_column('user_data', 'created_at')
    op.drop_column('category_tags', 'updated_at')
    op.drop_column('category_tags', 'created_at')
    op.drop_column('category_tags', 'tag_weight')
    op.alter_column('categories', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('categories', 'featured_rank')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'meta_keywords')
    op.drop_column('categories', 'meta_description')
    op.drop_column('categories', 'meta_title')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_category_features_id'), table_name='category_features')
    op.drop_table('category_features')
    op.drop_index(op.f('ix_category_analytics_id'), table_name='category_analytics')
    op.drop_table('category_analytics')
    # ### end Alembic commands ###
